# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 403)
        self.fl_list = QtWidgets.QListWidget(Dialog)
        self.fl_list.setGeometry(QtCore.QRect(20, 40, 211, 311))
        self.fl_list.setObjectName("fl_list")
        self.fl_info = QtWidgets.QTextBrowser(Dialog)
        self.fl_info.setGeometry(QtCore.QRect(240, 20, 241, 121))
        self.fl_info.setObjectName("fl_info")
        self.btn_cls = QtWidgets.QPushButton(Dialog)
        self.btn_cls.setGeometry(QtCore.QRect(410, 230, 81, 31))
        self.btn_cls.setObjectName("btn_cls")
        self.fl_pic = QtWidgets.QLabel(Dialog)
        self.fl_pic.setGeometry(QtCore.QRect(410, 150, 71, 71))
        self.fl_pic.setObjectName("fl_pic")
        self.gp_pick = QtWidgets.QComboBox(Dialog)
        self.gp_pick.setGeometry(QtCore.QRect(20, 20, 211, 22))
        self.gp_pick.setObjectName("gp_pick")
        self.gp_list = QtWidgets.QListWidget(Dialog)
        self.gp_list.setGeometry(QtCore.QRect(240, 170, 161, 181))
        self.gp_list.setObjectName("gp_list")
        self.btn_del_gp = QtWidgets.QPushButton(Dialog)
        self.btn_del_gp.setGeometry(QtCore.QRect(410, 260, 81, 31))
        self.btn_del_gp.setObjectName("btn_del_gp")
        self.btn_add_gp = QtWidgets.QPushButton(Dialog)
        self.btn_add_gp.setGeometry(QtCore.QRect(410, 320, 81, 31))
        self.btn_add_gp.setObjectName("btn_add_gp")
        self.new_gp_name = QtWidgets.QLineEdit(Dialog)
        self.new_gp_name.setGeometry(QtCore.QRect(410, 290, 81, 31))
        self.new_gp_name.setObjectName("new_gp_name")
        self.btn_unfl = QtWidgets.QPushButton(Dialog)
        self.btn_unfl.setGeometry(QtCore.QRect(240, 140, 81, 31))
        self.btn_unfl.setObjectName("btn_unfl")
        self.btn_homepage = QtWidgets.QPushButton(Dialog)
        self.btn_homepage.setGeometry(QtCore.QRect(20, 360, 461, 32))
        self.btn_homepage.setObjectName("btn_homepage")
        self.label_loading = QtWidgets.QLabel(Dialog)
        self.label_loading.setGeometry(QtCore.QRect(330, 150, 58, 16))
        self.label_loading.setText("")
        self.label_loading.setObjectName("label_loading")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_cls.setText(_translate("Dialog", "分类"))
        self.fl_pic.setText(_translate("Dialog", "picture"))
        self.btn_del_gp.setText(_translate("Dialog", "删除"))
        self.btn_add_gp.setText(_translate("Dialog", "新增"))
        self.btn_unfl.setText(_translate("Dialog", "取关"))
        self.btn_homepage.setText(_translate("Dialog", "go to homepage"))
